module.exports = {
    SET_LOADING      : 'SET_LOADING',
    SET_TOKEN        : 'SET_TOKEN',
    SET_USER         : 'SET_USER',
    SET_LOGIN_ERROR  : 'SET_LOGIN_ERROR',
    SET_LOGIN_SUCCESS: 'SET_SUCCESS',
    ACTION_LOGIN     : 'ACTION_LOGIN',
    ACTION_REGISTER  : 'ACTION_REGISTER'
}