export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const SET_LOADING       = 'SET_LOADING'
export const SET_TOKEN         = 'SET_TOKEN'
export const SET_USER          = 'SET_USER'
export const SET_LOGIN_ERROR   = 'SET_LOGIN_ERROR'
export const SET_LOGIN_SUCCESS = 'SET_SUCCESS'

export const FLUSH_REGISTER_ERROR_SUCCEESS = 'FLUSH_REGISTER_ERROR_SUCCEESS'
export const ACTION_LOGIN                  = 'ACTION_LOGIN'
export const ACTION_LOGOUT                 = 'ACTION_LOGOUT'
export const ACTION_REGISTER               = 'ACTION_REGISTER'
export const ACTION_GET_USER               = 'ACTION_GET_USER'

export const ACTION_SHOW_NOTIFICATION = 'ACTION_SHOW_NOTIFICATION'

export const ACTION_SAVE_USER_COMPANY_INFO = 'ACTION_SAVE_USER_COMPANY_INFO'
export const ACTION_SAVE_PROFILE_INFO      = 'ACTION_SAVE_PROFILE_INFO'
export const GET_USER_COMPANY              = 'GET_USER_COMPANY'
export const GET_IS_LOADED                 = 'GET_IS_LOADED'
export const ACTION_GET_USER_COMPANY       = 'ACTION_GET_USER_COMPANY'
export const SET_COMPANY                   = 'SET_COMPANY'
export const SET_LOADED                    = 'SET_LOADED'
export const SET_COMPANY_FIELD             = 'SET_COMPANY_FIELD'
export const SET_USER_FIELD                = 'SET_USER_FIELD'